name: Publish Image
on:
  # Triggers the workflow on push to matching branches
  push:
    branches:
    - main
  # (Optional) Allows users to trigger the workflow manually from the GitHub UI
  workflow_dispatch: {}
  # (Optional) Allow other workflows to use this workflow ant its outputs
  workflow_call: 
    outputs:
      image:
        description: The URI of the image
        value: ${{ jobs.build_image.outputs.image }}
    secrets:
      DUPLO_TOKEN:
        description: The token to use for Duplo API calls
        required: true

env:
  DUPLO_HOST: ${{ vars.DUPLO_HOST }}
  DUPLO_TENANT: ${{ vars.DUPLO_TENANT }}
  DUPLO_TOKEN: ${{ secrets.DUPLO_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1
    outputs:
      image: ${{ steps.build_image.outputs.uri }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Duplo Setup
      uses: duplocloud/actions@main

    - name: Build and Push Docker Image
      id: build_image
      uses: duplocloud/actions/build-image@build-image-updates
      with:
        platforms: linux/amd64 # linux/arm64 makes it take longer
        push: false
        tags: >
          latest
        build-args: >
          foo=bar
          ice_cream=chocolate
          name=${{ github.repository }}