name: Test
run-name: Testing Project
on: 
  workflow_dispatch: {}
  workflow_call: {}
jobs:
  build_test:
    name: Code Review
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 19
        cache: npm
    
    - name: Install
      run: npm ci

    - name: Audit Installation
      continue-on-error: true
      run: npm audit

    - name: Build Project
      run: npm run build:ci

    - name: Test
      run: npm test

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: ./dist/

    